apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-platform
data:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "user-events"
  MAILER_DSN: "smtp://mailhog:1025"
  MAILER_FROM: "no-reply@user-platform.local"
  POSTGRES_DB: "app"
  POSTGRES_USER: "app"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: user-platform
type: Opaque
stringData:
  APP_SECRET: "local-dev-not-secret-change-me"
  POSTGRES_PASSWORD: "app"
  DATABASE_URL: "postgresql://app:app@postgres:5432/app?serverVersion=16&charset=utf8"
