apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: user-platform
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: KAFKA_CONSUMER_GROUP
              value: "notification-service"
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              memory: 256Mi
